version: "3.7"

services: 
  database_fullStack:
    image: postgres
    container_name: database_fullStack
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fullStack
    volumes:
      - pgdata:/data/postgres


volumes: 
  pgdata:
    driver: local
